Portkey-Wallet/portkey-DID-server

- src/CAServer.Application/Verifier/VerifierAppService.cs
- src/CAServer.Redis/RedisCacheProvider.cs
> hotfix redis increase

- src/CAServer.ContractEventHandler/CAServerContractEventHandlerModule.cs
> fix: add signature module.

- src/CAServer.AuthServer/CAServerAuthServerModule.cs
- hotfix: add httpclient in authserver
> fix: add httpclient.

- src/CAServer.Application/Google/GoogleAppService.cs
- src/CAServer.HttpApi/Controllers/CAVerifierController.cs
- test/CAServer.Application.Tests/IpWhiteList/IpWhiteListMockTests.cs
- test/CAServer.Application.Tests/IpWhiteList/IpWhiteListTests.cs
> fix sms compatible logic

- src/CAServer.Application.Contracts/CAServer.Application.Contracts.csproj
- src/CAServer.Application.Contracts/Verifier/Dtos/VerifyTokenRequestDto.cs
- src/CAServer.Application.Contracts/Verifier/VerificationSignatureRequestDto.cs
- src/CAServer.Application.Contracts/Verifier/VerifierCodeOperationType.cs
- src/CAServer.Application.Contracts/Verifier/VierifierCodeRequestInput.cs
- src/CAServer.Application/Verifier/VerifierServerClient.cs
- test/CAServer.Application.Tests/VerifierCode/VerifierCodeTests.cs
> feat:slowmist report

- src/CAServer.Application.Contracts/CAActivity/ActivityConstants.cs
- src/CAServer.Application/CAActivity/UserActivityAppService.cs
- test/CAServer.Application.Tests/CAActivity/UserActivityAppServiceTests.cs
feature:add beango town event; 
bugfix:nftinfo is null
> feature:add beango town event; bugfix:nftinfo is null

- src/CAServer.Application.Contracts/CAActivity/ActivityConstants.cs
bugfix:
1、show price for bingotown
> add show pricew

- src/CAServer.Application/CAActivity/UserActivityAppService.cs
- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
> feat:optimize beangoTown

- src/CAServer.Application/Options/SwitchOptions.cs
- src/CAServer.Application/Verifier/VerifierServerClient.cs
- test/CAServer.Grain.Tests/ClusterFixture.cs
> feat:fix bug

- src/CAServer.HttpApi.Host/phone.json
> feat:add countries

- src/CAServer.Application/Options/SwitchOptions.cs
- src/CAServer.HttpApi.Host/appsettings.json
- src/CAServer.HttpApi/Controllers/CAVerifierController.cs
- src/CAServer.HttpApi/Controllers/TelegramAuthController.cs
Deactivate telegram login interface
> Deactivate telegram login interface

- src/CAServer.ContractEventHandler.Core/Application/IContractAppService.cs
- src/CAServer.ContractEventHandler.Core/Application/IContractProvider.cs
- src/CAServer.Grains/Grain/ApplicationHandler/ContractServiceConstant.cs
manager acceleration no force update
> manager acceleration no force update

- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
Desc：nft package hide inscription
> Fix: nft package hide inscription

- src/CAServer.ContractEventHandler.Core/Application/IContractAppService.cs
> add notLoginguardians

- src/CAServer.Application/CAAccount/CAAccountAppService.cs
- src/CAServer.Application/CAAccount/Provider/GuardianAddedCAHolderDto.cs
- test/CAServer.Application.Tests/CAAccount/RecoveryServiceTestMock.cs
- test/CAServer.Application.Tests/CAAccount/RevokeAccountMockTests.cs
Desc: fix revoke account fail because other account with unloginGuardian already be revoked
> fix revoke guardian fail

- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
> nft query optimized

- src/CAServer.Application/ContractService/ContractService.cs
- src/CAServer.HttpApi.Host/CAServer.HttpApi.Host.csproj
- src/CAServer.HttpApi.Host/CAServerHttpApiHostModule.cs
- src/CAServer.HttpApi/Controllers/CAAccountController.cs
- src/CAServer.HttpApi/Controllers/ContactController.cs
- src/CAServer.HttpApi/Controllers/RedPackageController.cs
- src/CAServer.Monitor/Interceptor/MonitorAttribute.cs
- src/CAServer.Monitor/Interceptor/MonitorInterceptor.cs
> performance monitor for CAServer, especially the transaction packaging
> performance monitor for CAServer, especially the transaction packaging

- src/CAServer.Application/CAAccount/CAAccountAppService.cs
- src/CAServer.Application/CAAccount/TransactionFeeAppService.cs
- src/CAServer.Application/Contacts/ContactAppService.cs
- src/CAServer.Application/Growth/GrowthAppService.cs
- src/CAServer.Application/Guardian/GuardianAppService.cs
- src/CAServer.Application/RedPackage/RedPackageAppService.cs
- src/CAServer.HttpApi/Controllers/CAAccountController.cs
- src/CAServer.HttpApi/Controllers/ContactController.cs
- src/CAServer.HttpApi/Controllers/RedPackageController.cs
adjust the postion of the attribute 'monitor'
> adjust the postion of the attribute 'monitor'

- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
1.Fix nft traits;
2.Optimize query nftItem interface
> Fix nft traits

- src/CAServer.Application/Options/DepositOptions.cs
- src/CAServer.Application/Transfer/TransferAppService.cs
Fix deposit network confirmation count
Issue: #337
> Fix deposit network confirmation count

- src/CAServer.Application/CAActivity/UserActivityAppService.cs
fix activity list nft url.
Issue: #341
> Fix activity list nft url.

- src/CAServer.CoinGeckoApi/TokenPriceProvider.cs
Fix get sgr price error.
Issue: #390
> Fix get sgr price error.

- src/CAServer.Application/Transfer/Proxy/ETransferProxyService.cs
> Remove offline

- src/CAServer.Application/CAAccount/CAAccountAppService.cs
add verify address compatible logic
> add verify address compatible logic

- src/CAServer.Application/Growth/GrowthStatisticAppService.cs
> fix hasmter data repair

- src/CAServer.Application.Contracts/Commons/ContractServiceConstant.cs
- src/CAServer.Application/Options/ETransferOptions.cs
- src/CAServer.Application/Transfer/Proxy/IETransferClientProvider.cs
Deposit support ton.
Issue: #727
> Deposit support ton

- src/CAServer.Application.Contracts/Commons/HMACSHA256Helper.cs
- src/CAServer.Application.Contracts/Growth/Dtos/TonGiftsRequestDto.cs
- src/CAServer.Application.Contracts/Growth/Dtos/TonGiftsResponseDto.cs
- src/CAServer.Application.Contracts/Growth/Dtos/ValidateHamsterScoreResponseDto.cs
- src/CAServer.Application.Contracts/Growth/IGrowthStatisticAppService.cs
- src/CAServer.Application/CAActivity/Provider/ActivityProvider.cs
- src/CAServer.Application/CAActivity/Provider/IActivityProvider.cs
- src/CAServer.Application/Growth/GrowthStatisticAppService.cs
- src/CAServer.Application/Options/TonGiftsOptions.cs
- src/CAServer.Application/Verifier/VerifierAppService.cs
- src/CAServer.EntityEventHandler.Core/Worker/TonGiftsValidateWorker.cs
- src/CAServer.HttpApi/Controllers/GrowthController.cs
> Add TonGift activity.

- src/CAServer.Application/CAActivity/Provider/ActivityProvider.cs
- src/CAServer.Application/Growth/GrowthStatisticAppService.cs
Fix pea.ai task api error.
Issue: #749
> Fix pea.ai task api error.

- src/CAServer.ContractEventHandler.Core/Application/IContractAppService.cs
- src/CAServer.ContractEventHandler.Core/Application/ZkLoginWorkerOptions.cs
- src/CAServer.ContractEventHandler.Core/Worker/SyncronizeZkloginPoseidonHashWorker.cs
1. socail recovery acceleration logic #763
> fix social recovery accelerate logic

- src/CAServer.Application/Tokens/TokenDisplayAppService.cs
- src/CAServer.Application/Tokens/TokenNftAppService.cs
- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
- test/CAServer.Application.Tests/CAAccount/RecoveryServiceTests.cs
- test/CAServer.Application.Tests/CAServerApplicationTestBase.cs
Solve the problem of assets showing negative values.
#792
> Asset balance

- src/CAServer.Application.Contracts/DataReporting/Dtos/AccountReportDto.cs
- src/CAServer.Application.Contracts/DataReporting/Etos/AccountReportEto.cs
- src/CAServer.Application.Contracts/DataReporting/IDataReportAppService.cs
- src/CAServer.Application/CAServerApplicationAutoMapperProfile.cs
- src/CAServer.Application/DataReporting/DataReportAppService.cs
- src/CAServer.ContractEventHandler.Core/CAServerContractEventHandlerAutoMapperProfile.cs
- src/CAServer.Domain.Shared/EnumType/AccountOperationType.cs
- src/CAServer.Domain.Shared/EnumType/ClientType.cs
- src/CAServer.Domain/Entities/Es/AccountReportIndex.cs
- src/CAServer.EntityEventHandler.Core/CAServerEventHandlerAutoMapperProfile.cs
- src/CAServer.EntityEventHandler.Core/ReportHandler.cs
- src/CAServer.HttpApi/Controllers/DataReportController.cs
Statistic registration source
Issue: #782
> Statistic registration source

- src/CAServer.Application.Contracts/Commons/CaPageResultDto.cs
- src/CAServer.Application.Contracts/Commons/ContractServiceConstant.cs
- src/CAServer.Application.Contracts/Tokens/Dtos/ChangeTokenDisplayDto.cs
- src/CAServer.Application.Contracts/Tokens/Dtos/GetTokenInfosV2RequestDto.cs
- src/CAServer.Application.Contracts/Tokens/Dtos/GetTokenListV2Dto.cs
- src/CAServer.Application.Contracts/Tokens/Dtos/GetTokenListV2RequestDto.cs
- src/CAServer.Application.Contracts/Tokens/Dtos/GetUserTokenV2Dto.cs
- src/CAServer.Application.Contracts/Tokens/IUserTokenV2AppService.cs
- src/CAServer.Application/CAServerApplicationAutoMapperProfile.cs
- src/CAServer.Application/CAServerApplicationModule.cs
- src/CAServer.Application/Options/AddTokenOptions.cs
- src/CAServer.Application/Tokens/UserTokenV2AppService.cs
- src/CAServer.HttpApi/Controllers/UserTokenV2Controller.cs
1、portkey main-side chain asset display optimized interface development - Add token
Issue: #812
> Portkey main-side chain asset display optimized

- src/CAServer.Application.Contracts/CAAccount/Dtos/RegisterRequestDto.cs
- src/CAServer.Application.Contracts/CAAccount/Etos/HolderExtraInfoCompletedEto.cs
- src/CAServer.Application.Contracts/CAAccount/Etos/HolderExtraInfoEto.cs
- src/CAServer.Application/CAAccount/CAAccountAppService.cs
- src/CAServer.Application/IpInfo/IIpInfoClient.cs
- src/CAServer.Application/IpInfo/IpInfoClient.cs
- src/CAServer.Application/IpInfo/IpServiceSettingOptions.cs
- src/CAServer.Domain/Entities/Es/HolderStatisticIndex.cs
- src/CAServer.EntityEventHandler.Core/CAAccountHandler.cs
- src/CAServer.EntityEventHandler.Core/CAServerEventHandlerAutoMapperProfile.cs
- src/CAServer.EntityEventHandler.Core/HolderStatisticHandler.cs
1、obtain holder source of activity and country
Issue: #838
> holder info statistic

- src/CAServer.Application.Contracts/CAAccount/IAppleZkProvider.cs
- src/CAServer.Application/CAAccount/Provider/AppleZkProvider.cs
- src/CAServer.Application/CAAccount/Provider/GoogleZkProvider.cs
- src/CAServer.Application/Verifier/VerifierAppService.cs
- src/CAServer.Application/Verifier/VerifierServerClient.cs
1. Transaction Email Optimization #849
> Transaction Email Optimization

- src/CAServer.Application.Contracts/CAAccount/Dtos/AccountResultDto.cs
- src/CAServer.Application.Contracts/CAAccount/Dtos/ManagerCacheDto.cs
- src/CAServer.Application.Contracts/CAAccount/Dtos/ManagerDto.cs
- src/CAServer.Application.Contracts/CAAccount/Dtos/ProverResponse.cs
- src/CAServer.Application.Contracts/CAAccount/Dtos/RecoveryRequestDto.cs
- src/CAServer.Application.Contracts/CAAccount/Dtos/VerificationDocInfo.cs
- src/CAServer.Application.Contracts/CAAccount/Enums/OperationTypeInContract.cs
- src/CAServer.Application.Contracts/CAAccount/ICAAccountAppService.cs
- src/CAServer.Application.Contracts/CAAccount/IPreValidationProvider.cs
- src/CAServer.Application.Contracts/CAAccount/PreValidationType.cs
- src/CAServer.Application.Contracts/CAAccount/RequestSource.cs
- src/CAServer.Application.Contracts/Commons/ContractServiceConstant.cs
- src/CAServer.Application.Contracts/Contracts/CaContract.g.cs
- src/CAServer.Application.Contracts/Contracts/CaContractImpl.c.cs
- src/CAServer.Application.Contracts/Contracts/CaContractImpl.g.cs
- src/CAServer.Application.Contracts/Verifier/VerifierServerInfo.cs
- src/CAServer.Application/CAAccount/CAAccountAppService.cs
- src/CAServer.Application/CAAccount/Provider/PreValidation/IPreValidationStrategy.cs
- src/CAServer.Application/CAAccount/Provider/PreValidation/PreValidationProvider.cs
- src/CAServer.Application/CAAccount/Provider/PreValidation/SignaturePreValidationProvider.cs
- src/CAServer.Application/CAAccount/Provider/PreValidation/ZkLoginPreValidationProvider.cs
- src/CAServer.Application/CAAccount/Provider/ZkLoginProverOptions.cs
- src/CAServer.Application/CAServerApplicationAutoMapperProfile.cs
- src/CAServer.Application/CAServerApplicationModule.cs
- src/CAServer.Application/Common/ContractProvider.cs
- src/CAServer.Application/Common/GetVerifierServerProvider.cs
- src/CAServer.AuthServer/SignatureGrantHandler.cs
- src/CAServer.HttpApi/Controllers/CAAccountController.cs
1. TG login process Optimization #817
> TG login process Optimization

- src/CAServer.Application/Guardian/GuardianAppService.cs
- src/CAServer.HttpApi/Controllers/CAAccountController.cs
1. Monitoring of login process time consumption #856
> Monitoring of login process time consumption

- src/CAServer.Application/CAAccount/CAAccountAppService.cs
- src/CAServer.Domain/Entities/Es/HolderStatisticIndex.cs
- src/CAServer.EntityEventHandler.Core/HolderStatisticHandler.cs
Optimize the user statistics function
Issue: #863
> Optimize holder statistic.

- src/CAServer.Application/CAAccount/CAAccountAppService.cs
- src/CAServer.AuthServer/SignatureGrantHandler.cs
1. Add logs for login interface and JWT token query interface
> Telegram Login Optimization Monitor Log

- src/CAServer.Application.Contracts/Commons/ContractServiceConstant.cs
- src/CAServer.Application.Contracts/Http/Dtos/SyncStateDto.cs
- src/CAServer.Application/CAActivity/UserActivityAppService.cs
- src/CAServer.Application/CAServerApplicationModule.cs
- src/CAServer.Application/Growth/GrowthStatisticAppService.cs
- src/CAServer.Application/Growth/Provider/GrowthProvider.cs
- src/CAServer.Application/IGraphQLProvider.cs
- src/CAServer.Application/Tokens/TokenDisplayAppService.cs
- src/CAServer.Application/Tokens/TokenNftAppService.cs
- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
Portkey backend service compatible with aefinder-v2
Issue: #866
> Compatible with aefinder-v2

- src/CAServer.Application/Tokens/TokenNftAppService.cs
Fix user asset list display
Issue: #869
> Fix user asset list display.

- src/CAServer.Application.Contracts/CAAccount/Dtos/ManagerCacheDto.cs
- src/CAServer.Application.Contracts/CAAccount/IPreValidationProvider.cs
- src/CAServer.Application/CAAccount/CAAccountAppService.cs
- src/CAServer.Application/CAAccount/Provider/PreValidation/PreValidationProvider.cs
- src/CAServer.AuthServer/CAServer.AuthServer.csproj
- src/CAServer.AuthServer/CAServerAuthServerModule.cs
- src/CAServer.AuthServer/SignatureGrantHandler.cs
1. Tg Login Optimization Api Adjustment
> Tg Login Optimization Api Adjustment

- src/CAServer.Application.Contracts/CAAccount/IPreValidationProvider.cs
- src/CAServer.Application.Contracts/Guardian/GuardianBase.cs
- src/CAServer.Application.Contracts/Guardian/IGuardianAppService.cs
- src/CAServer.Application/CAAccount/CAAccountAppService.cs
- src/CAServer.Application/CAAccount/Provider/AppleZkProvider.cs
- src/CAServer.Application/CAAccount/Provider/GoogleZkProvider.cs
- src/CAServer.Application/CAAccount/Provider/PreValidation/PreValidationProvider.cs
- src/CAServer.Application/CAServerApplicationAutoMapperProfile.cs
- src/CAServer.Application/CAServerApplicationModule.cs
- src/CAServer.Application/Common/GetVerifierServerProvider.cs
- src/CAServer.Application/CryptoGift/CryptoGiftAppService.cs
- src/CAServer.Application/Guardian/GuardianAppService.cs
- src/CAServer.Application/Guardian/Provider/GuardianProvider.cs
- src/CAServer.Application/Guardian/Provider/IGuardianProvider.cs
- src/CAServer.Application/Options/LoginCacheOptions.cs
- src/CAServer.ContractEventHandler.Core/Worker/SendingTransactionInfoByEmailAfterApprovalWorker.cs
- src/CAServer.HttpApi/Controllers/CAAccountController.cs
1. telegram login process acceleration, see  #899
> Telegram Login Optimization

- src/CAServer.Application/Guardian/GuardianAppService.cs
- src/CAServer.Application/Guardian/Provider/GuardianProvider.cs
1. Telegram Login Optimization #900
> Telegram Login Optimization #900

- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
Fix SGR-1 cross chain transfer fail.
Issue: #910
> Fix SGR-1 cross chain transfer fail

- src/CAServer.Application.Contracts/Verifier/IVerifierAppService.cs
- src/CAServer.Application.Contracts/Verifier/VerifierServerBasicInfo.cs
- src/CAServer.Application/Common/GetVerifierServerProvider.cs
- src/CAServer.Application/Guardian/GuardianAppService.cs
- src/CAServer.Application/Options/LoginCacheOptions.cs
- src/CAServer.Application/Verifier/VerifierAppService.cs
- src/CAServer.HttpApi/Controllers/CAVerifierController.cs
1. Telegram Login Optimization phase3 #938
> Telegram Login Optimization phase3

- src/CAServer.Application.Contracts/Commons/AddressHelper.cs
- src/CAServer.Application.Contracts/Commons/ContractServiceConstant.cs
- src/CAServer.Application.Contracts/Commons/ShiftChainHelper.cs
- src/CAServer.Application.Contracts/Commons/TokenHelper.cs
- src/CAServer.Application.Contracts/UserAssets/Dtos/IndexerNftItemInfos.cs
- src/CAServer.Application/AddressBook/AddressBookAppService.cs
- src/CAServer.Application/CAActivity/UserActivityAppService.cs
- src/CAServer.Application/Tokens/UserTokenAppService.cs
- src/CAServer.Application/Transfer/ShiftChainService.cs
- src/CAServer.Application/UserAssets/Provider/IUserAssetsProvider.cs
- src/CAServer.Application/UserAssets/Provider/UserAssetsProvider.cs
- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
- src/CAServer.Domain/Entities/Es/AddressBookIndex.cs
> Fix revamp bug

- src/CAServer.Application.Contracts/AddressBook/IAddressBookAppService.cs
- src/CAServer.Application.Contracts/Commons/AddressHelper.cs
- src/CAServer.Application/AddressBook/AddressBookAppService.cs
- src/CAServer.Application/CAActivity/Provider/UserContactProvider.cs
- src/CAServer.HttpApi/Controllers/AddressBookController.cs
> Revamp bug fix

- src/CAServer.Application.Contracts/Commons/ShiftChainHelper.cs
> Revamp bug fix.

- src/CAServer.ContractEventHandler.Core/Application/IContractAppService.cs
- src/CAServer.ContractEventHandler.Core/Application/IContractProvider.cs
- src/CAServer.ContractEventHandler.Core/CAContractEventHandler.cs
Some accounts failed manager acceleration.
#993
> Fix manager acceleration

- src/CAServer.Application.Contracts/Contacts/Dtos/CreateUpdateContactDto.cs
- src/CAServer.Application.Contracts/Contacts/IContactAppService.cs
- src/CAServer.Application/Contacts/ContactAppService.cs
- src/CAServer.EntityEventHandler.Core/CAHolderHandler.cs
Contact function changes after removing IM.
Issue: #976
> Remove IM module

- src/CAServer.Application/Tokens/TokenNftAppService.cs
> Swap elephant image.

- src/CAServer.Application.Contracts/Tokens/Dtos/GetTokenInfoDto.cs
- src/CAServer.Application.Contracts/Tokens/Dtos/UserTokenDto.cs
- src/CAServer.Application.Contracts/UserAssets/Dtos/IndexerTokenInfo.cs
- src/CAServer.Application/CAActivity/Provider/ActivityProvider.cs
- src/CAServer.Application/CAActivity/UserActivityAppService.cs
- src/CAServer.Application/CAServerApplicationAutoMapperProfile.cs
- src/CAServer.Application/Options/TokenListOptions.cs
- src/CAServer.Application/Tokens/Cache/TokenCacheProvider.cs
- src/CAServer.Application/Tokens/Provider/IndexerTokens.cs
- src/CAServer.Application/Tokens/Provider/TokenProvider.cs
- src/CAServer.Application/Tokens/TokenAppService.cs
- src/CAServer.Application/Tokens/TokenDisplayAppService.cs
- src/CAServer.Application/Tokens/TokenNftAppService.cs
- src/CAServer.Application/Tokens/UserTokenAppService.cs
- src/CAServer.Application/Tokens/UserTokenV2AppService.cs
- src/CAServer.Application/UserAssets/IAssetsLibraryProvider.cs
- src/CAServer.Application/UserAssets/Provider/UserAssetsProvider.cs
- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
- src/CAServer.Application/UserSecurity/UserSecurityAppService.cs
- src/CAServer.Domain/Entities/Es/UserTokenIndex.cs
- src/CAServer.EntityEventHandler.Core/CAServerEventHandlerAutoMapperProfile.cs
- src/CAServer.Grains/Grain/Tokens/UserTokens/UserTokenGrain.cs
Retrieve ft token images from blockchain.
> Ft token image url

- src/CAServer.Application.Contracts/Commons/ShiftChainHelper.cs
- src/CAServer.Application/AddressBook/AddressBookAppService.cs
> Address book address validate

- src/CAServer.Application.Contracts/Transfer/Dtos/GetDepositInfoDto.cs
- src/CAServer.HttpApi/Controllers/CAVerifierController.cs
1. Support etransfer new deposit fee. close #1029
> Support etransfer new deposit fee

- src/CAServer.HttpApi/Controllers/CAVerifierController.cs
1. Fix email register intercept. close #1031
> Fix email register intercept

- src/CAServer.Application.Contracts/UserAssets/IUserAssetsAppService.cs
- src/CAServer.Application/Market/MarketAppService.cs
- src/CAServer.Application/UserAssets/UserAssetsAppService.cs
- src/CAServer.HttpApi/Controllers/CAMarketController.cs
- src/CAServer.HttpApi/Controllers/UserAssetsController.cs
1、add market api
2、support eoa nftitem
> support eoa api

- .github/workflows/mainnet-package.yaml
- .github/workflows/testnet-package.yaml
- src/CAServer.Application/Options/ETransferOptions.cs
- src/CAServer.Application/Transfer/ShiftChainService.cs
1、filter etransfer and ebridge sendnetwork
> filter sendnetwork
